---
env:
    browser: true
    es6: true
    node: true
extends: 'eslint:recommended'
globals:
    $: false
    gapi: false
    moment: false
rules:
    accessor-pairs: error
    array-bracket-spacing:
        - error
        - never
    array-callback-return: error
    arrow-body-style: warn
    arrow-parens: error
    arrow-spacing:
        - warn
        -
            after: true
            before: true
    block-scoped-var: error
    block-spacing: error
    brace-style: warn
    callback-return: error
    camelcase:
        - warn
        - properties: never
    class-methods-use-this: error
    comma-dangle: warn
    comma-spacing: warn
    comma-style: warn
    computed-property-spacing: warn
    consistent-return: error
    consistent-this: error
    curly: warn
    default-case: error
    dot-location: error
    dot-notation: error
    eol-last: warn
    eqeqeq: error
    func-call-spacing: error
    func-name-matching: error
    func-names:
        - error
        - never
    func-style:
        - warn
        - declaration
    generator-star-spacing: warn
    global-require: error
    guard-for-in: error
    handle-callback-err: error
    indent:
        - warn
        - tab
    key-spacing: warn
    lines-around-comment: warn
    lines-around-directive: warn
    multiline-ternary:
        - warn
        - never
    new-cap: error
    new-parens: error
    no-alert: warn
    no-array-constructor: error
    no-await-in-loop: error
    no-bitwise: error
    no-caller: error
    no-catch-shadow: error
    no-compare-neg-zero: error
    no-confusing-arrow: warn
    no-console: off # TODO: Disable this
    no-continue: error
    no-div-regex: error
    no-duplicate-imports: error
    no-else-return: error
    no-empty-function: error
    no-eq-null: error
    no-eval: error
    no-extend-native: error
    no-extra-bind: error
    no-extra-label: error
    no-extra-parens: error
    no-floating-decimal: error
    no-implicit-coercion: error
    no-implied-eval: error
    no-invalid-this: error
    no-iterator: error
    no-label-var: error
    no-labels: error
    no-lone-blocks: error
    no-lonely-if: error
    no-loop-func: error
    no-mixed-operators: error
    no-mixed-requires: error
    no-mixed-spaces-and-tabs:
        - warn
        - smart-tabs
    no-multi-assign: error
    no-multi-spaces: error
    no-multi-str: error
    no-multiple-empty-lines: error
    no-native-reassign: error
    no-negated-condition: error
    no-negated-in-lhs: error
    no-nested-ternary: error
    no-new: error
    no-new-func: error
    no-new-object: error
    no-new-require: error
    no-new-wrappers: error
    no-octal-escape: error
    no-param-reassign: error
    no-path-concat: error
    no-process-exit: error
    no-proto: error
    no-prototype-builtins: error
    no-restricted-globals: error
    no-restricted-imports: error
    no-restricted-modules: error
    no-restricted-properties: error
    no-restricted-syntax: error
    no-return-assign: error
    no-return-await: error
    no-script-url: error
    no-self-compare: error
    no-sequences: error
    no-shadow: error
    no-shadow-restricted-names: error
    no-spaced-func: error
    no-sync: error
    no-template-curly-in-string: error
    no-throw-literal: error
    no-trailing-spaces: error
    no-undef-init: error
    no-undefined: error
    no-underscore-dangle: error
    no-unmodified-loop-condition: error
    no-unneeded-ternary: error
    no-unused-expressions: error
    no-use-before-define: error
    no-useless-call: error
    no-useless-computed-key: error
    no-useless-concat: error
    no-useless-constructor: error
    no-useless-escape: error
    no-useless-rename: error
    no-useless-return: error
    no-var: warn
    no-void: error
    no-warning-comments: error
    no-whitespace-before-property: error
    no-with: error
    nonblock-statement-body-position: error
    object-curly-newline: error
    object-curly-spacing: error
    object-shorthand:
        - warn
        - consistent-as-needed
    operator-assignment:
        - error
        - always
    operator-linebreak: error
    padded-blocks:
        - warn
        - never
    prefer-const: warn
    prefer-numeric-literals: warn
    prefer-promise-reject-errors: warn
    prefer-reflect: warn
    prefer-rest-params: warn
    prefer-spread: warn
    prefer-template: warn
    quote-props:
        - warn
        - as-needed
    quotes:
        - warn
        - single
        -
            avoidEscape: true
            allowTemplateLiterals: true
    radix: error
    require-await: error
    rest-spread-spacing: warn
    semi: error
    semi-spacing: warn
    sort-imports: error
    sort-vars: error
    space-in-parens:
        - warn
        - never
    space-infix-ops: error
    space-unary-ops: error
    spaced-comment:
        - error
        - always
    strict:
        - error
        - never
    symbol-description: error
    template-curly-spacing: error
    template-tag-spacing: error
    unicode-bom:
        - error
        - never
    valid-jsdoc: error
    vars-on-top: error
    wrap-iife: error
    wrap-regex: error
    yield-star-spacing: error
    yoda:
        - error
        - never
