sudo: true
dist: trusty

install:
    - nvm install node
    - gem install html-proofer
    - npm install -g eslint
    - npm install -g stylelint

script:
    - htmlproofer --check-html --check-favicon --enforce-https
    - eslint js/**
    - stylelint css/**

branches:
  only:
    - master

notifications:
    email: false
